### ISSUE TITLE
Blender 2.9 and Zbrush 2021 Error

### ISSUE THREAD

**Issue by LOLDesu** [JoseConseco/GoB#181]
Traceback (most recent call last):
  File "C:\Users\steph\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\GoB-GoZ-Blender_28\GoB.py", line 1310, in execute
    Popen([PATH_ZBRUSH, PATH_SCRIPT])
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.90\python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.90\python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

Tried everything can't seem to figure out why there is an error?

**Comment by kromar** [comment]
@LOLDesu  please check this post since its about the same problem thanks. https://github.com/JoseConseco/GoB/issues/173
