### ISSUE TITLE
Can't export mesh to zbrush

### ISSUE THREAD

**Issue by justcloud0607** [JoseConseco/GoB#186]
Traceback (most recent call last):
  File "C:\Users\Hyperbot\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\GoB-master\GoB.py", line 1256, in execute
    shutil.copytree(source_GoZ_Info, target_GoZ_Info, symlinks=True)            
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\shutil.py", line 324, in copytree
    os.makedirs(dst)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] 當檔案已存在時，無法建立該檔案。: 'False/GoZApps/Blender/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hyperbot\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\GoB-master\GoB.py", line 1267, in execute
    with open(f"{PATH_GOZ}/GoZBrush/GoZ_Application.txt", 'wt') as GoZ_Application:
FileNotFoundError: [Errno 2] No such file or directory: 'False/GoZBrush/GoZ_Application.txt'

location: <unknown location>:-1

Using Blender 2.90.1/GoB 3.4.9

**Comment by kromar** [comment]
can you try to run the GoZ repair in the zbrush and see if that fixes the problem? seems like some of the GoZ folders are not around
![image](https://user-images.githubusercontent.com/1472884/97920263-7bb9c880-1d59-11eb-947c-462ae313dd82.png)
