### ISSUE TITLE
Can't export a mesh

### ISSUE THREAD

**Issue by Werlious309** [JoseConseco/GoB#242]
hello! right now i installed add-on in blender, but i have error that always pop up:
Python: Traceback (most recent call last):
  File "D:\Games\Steam\steamapps\common\Blender\2.92\scripts\addons\gob\GoB.py", line 1237, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "D:\Games\Steam\steamapps\common\Blender\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\Games\Steam\steamapps\common\Blender\2.92\scripts\addons\gob\GoB.py", line 1047, in execute
    shutil.copytree(source_GoZ_Info, target_GoZ_Info, symlinks=True)            
  File "D:\Games\Steam\steamapps\common\Blender\2.92\python\lib\shutil.py", line 318, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] System nie może odnaleźć określonej ścieżki: 'D:\\Games\\Steam\\steamapps\\common\\Blender\\2.92\\scripts\\addons\\gob/Blender/'

location: D:\Games\Steam\steamapps\common\Blender\2.92\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1

**Comment by kromar** [comment]
hi, please try the latest version and see if the error is resolved.

https://github.com/JoseConseco/GoB/releases/tag/v3_5_52
