### ISSUE TITLE
Fresh Install, UnboundLocalError: local variable 'PATH_GOZ' referenced before assignment

### ISSUE THREAD

**Issue by cherrerajobs** [JoseConseco/GoB#304]
GoB Version: 3.5.71
Zbrush Location being set to: C:\Program Files\Pixologic\ZBrush 2022\ZBrush.exe

![image](https://user-images.githubusercontent.com/8894763/165892855-109b6074-f2b3-47cd-8111-7ee197e6b142.png)

Error:
```
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\GoB\GoB.py", line 1277, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Users\User\Desktop\Blender\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\GoB\GoB.py", line 1064, in execute
    PATH_GOZ = override_public_pixologic_path()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\GoB\GoB.py", line 1283, in override_public_pixologic_path
    return PATH_GOZ
UnboundLocalError: local variable 'PATH_GOZ' referenced before assignment

location: C:\Users\User\Desktop\Blender\3.1\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1
```

Relevant section GoB.py:
```
def override_public_pixologic_path():
    if prefs().custom_pixologoc_path:
        PATH_GOZ =  prefs().pixologoc_path        
    return PATH_GOZ
```

**Comment by kromar** [comment]
thanks for the report, this should be fixed in the latest master (v3_5_72) https://github.com/JoseConseco/GoB/archive/refs/heads/master.zip

**Comment by cherrerajobs** [comment]
Confirmed working! Thanks!

**Comment by SbstnDC** [comment]
@cherrerajobs Hi, other way to fix it, re install goz from gob like in image attach> 
![image](https://user-images.githubusercontent.com/22725270/166499227-0fe93aae-51f7-48a2-b2af-fb03a34c4703.png)
