### ISSUE TITLE
Can't install addon in linux

### ISSUE THREAD

**Issue by kadattack** [JoseConseco/GoB#320]
I'm using Wine to run Zbrush in linux while using Blender 3.1 natively.
I tried installing the GoB addon but get this error
`Traceback (most recent call last):
  File "/home/newuser/BlenderProjects/blender-3.2.0-linux-x64/3.2/scripts/modules/addon_utils.py", line 371, in enable
    mod.register()
  File "/home/newuser/.config/blender/3.2/scripts/addons/GoB-master/__init__.py", line 59, in register
    [bpy.utils.register_class(c) for c in classes]
  File "/home/newuser/.config/blender/3.2/scripts/addons/GoB-master/__init__.py", line 59, in <listcomp>
    [bpy.utils.register_class(c) for c in classes]
ValueError: bpy_struct "GoB_Preferences" registration error: 'pixologoc_path' StringProperty could not register (see previous error)

Traceback (most recent call last):
  File "/home/newuser/BlenderProjects/blender-3.2.0-linux-x64/3.2/scripts/modules/addon_utils.py", line 371, in enable
    mod.register()
  File "/home/newuser/.config/blender/3.2/scripts/addons/GoB-master/__init__.py", line 59, in register
    [bpy.utils.register_class(c) for c in classes]
  File "/home/newuser/.config/blender/3.2/scripts/addons/GoB-master/__init__.py", line 59, in <listcomp>
    [bpy.utils.register_class(c) for c in classes]
ValueError: register_class(...): already registered as a subclass 'GoB_OT_import'
`
Is this error due to me using Linux and the addon not able to find zbrush?
Can i manually edit this path to fix it?

**Comment by kromar** [comment]
hmm so far there is no support for linux, since i dont have such a setup and dont know the paths i cant really test it. What i could do is expose the paths which are at the moment hard coded depending on the system so they could be changed.

however i think you get that error due to a other issue which i believe should be fixed in the latest master (whenever you post a bug report it would be good to get the version of the addon you are using) maybe you can try this and see if that fixes the error you got. And in addition there should already be a option to change the pixologic path manually so maybe that already makes it work.
https://user-images.githubusercontent.com/1472884/165620819-3f8b1aaf-9ad5-446f-b0fb-4f33e6b8b2d1.png

GoB version 3_5_73
https://github.com/JoseConseco/GoB/archive/refs/heads/master.zip

**Comment by fislysandi** [comment]
you can always setup a debian WSL 2 from your terminal and launch blender this way you can test linux without installing a vm,

**Comment by fislysandi** [comment]
i REALLY want this feature.
