### ISSUE TITLE
the application does not work and gives an error

### ISSUE THREAD

**Issue by artberesta** [JoseConseco/GoB#400]
the application does not work and gives an error
![2023-01-27 15-26-27 Unable To Open File](https://user-images.githubusercontent.com/123745320/215101354-15b21431-3beb-475b-b026-236dfade5115.jpg)
![2023-01-27 15-08-26 Blender  E  YandexDisk blender маска ушки blend](https://user-images.githubusercontent.com/123745320/215101358-d3b4696c-c112-4416-8332-d07f8155a646.jpg)

**Comment by kromar** [comment]
please give more information what versions and operating system you are using and how this can be reproduced.

**Comment by artberesta** [comment]
Windows 10 Pro
Blender 3.4.0
ZBrush 2022.0.5.0
https://www.youtube.com/watch?v=i39irrVXbTk&t=143s
I installed it and set it up using this video

**Comment by artberesta** [comment]
bpy.ops.object.editmode_toggle()
bpy.ops.machin3.edit_mode()
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\GoB-master\GoB.py", line 1398, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\GoB-master\GoB.py", line 1182, in execute
    shutil.copytree(source_GoZ_Info, target_GoZ_Info, symlinks=True)            
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\shutil.py", line 558, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'C:\\Users\\Public\\Pixologic/GoZApps/Blender/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\GoB-master\GoB.py", line 1194, in execute
    with open(os.path.join(f"{PATH_GOZ}/GoZBrush/GoZ_Application.txt"), 'wt') as GoZ_Application:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Public\\Pixologic/GoZBrush/GoZ_Application.txt'
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113

**Comment by artberesta** [comment]
[ошибка.txt](https://github.com/JoseConseco/GoB/files/10529631/default.txt)
[ошибка2.txt](https://github.com/JoseConseco/GoB/files/10529632/2.txt)

**Comment by artberesta** [comment]
Thank you very much for your help

**Comment by artberesta** [comment]
![Screenshot_2023-01-29-21-35-28-407_org mozilla firefox](https://user-images.githubusercontent.com/123745320/215348309-015efff0-101b-44f9-8715-25f9fd5888cb.jpg)

**Comment by artberesta** [comment]
Hello.
I can't figure out the program.
Does not work.
It's a pity.
The right program

**Comment by danjaworsky** [comment]
More information: this file does not exist in this path, as the error says. 

I solved this issue by following instructions on reinstalling GOZ inside Zbrush. So this is a GOZ in Zbrush issue. 
Perhaps this will help someone. Maybe put it somewhere in the readme? 

https://www.zbrushcentral.com/t/goz-isnt-working/387999/6

Basically, you have to get rid of the shared GOZ files on your machine
navigate to the Zbrush installation location
go into 'troublshooting help'
run the goz for zbrush installer. 

Next time you click GOZ, You'll be asked to relink the applications.
