### ISSUE TITLE
Update GoB for Blender 4.0

### ISSUE THREAD

**Issue by Liferocka** [JoseConseco/GoB#418]
Does GOB work with Blender 4.0?  I get and error. 
![Screen Shot 2023-06-15 at 6 07 03 PM](https://github.com/JoseConseco/GoB/assets/50764172/6f76e1bd-7718-4742-b667-97a10de99e3b)

**Comment by Liferocka** [comment]
Python: Traceback (most recent call last):
  File "/Users/lifepro/Library/Application Support/Blender/4.0/scripts/addons/JoseConseco-GoB-407bade/GoB.py", line 1267, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "/Applications/Blender 4.0.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/lifepro/Library/Application Support/Blender/4.0/scripts/addons/JoseConseco-GoB-407bade/GoB.py", line 1181, in execute
    remove_internal_faces(obj)
  File "/Users/lifepro/Library/Application Support/Blender/4.0/scripts/addons/JoseConseco-GoB-407bade/GoB.py", line 1744, in remove_internal_faces
    bpy.ops.object.mode_set(bpy.context.copy(), mode='EDIT')
  File "/Applications/Blender 4.0.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "/Applications/Blender 4.0.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
Location: /Applications/Blender 4.0.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py:109

**Comment by schroef** [comment]
Seems bpy.xontext.copy is changed the n 4.0
Perhapsnchecl api changee

**Comment by kromar** [comment]
I pushed some fixes, i removed face sets as they have been removed from blender 4.0 and i think it should be possible with 4.0 to tap into the sculpt face sets instead. 
https://github.com/kromar/blender_GoB/tree/update-for-blender-4.0
https://github.com/kromar/blender_GoB/archive/refs/heads/update-for-blender-4.0.zip

**Comment by Liferocka** [comment]
Thanks I sadly get an error when trying to turn on the add on- I installed it, then when I go to click the Ceck box, to turn it on, I get this pop up.  

![Screen Shot 2023-08-26 at 4 51 45 PM](https://github.com/JoseConseco/GoB/assets/50764172/feaa9b67-4910-46fb-8352-96e1bf054413)

**Comment by kromar** [comment]
I suspect the . in the file name, i renamed the branch so you can try this one:
https://github.com/kromar/blender_GoB/tree/update-for-blender-4
https://github.com/kromar/blender_GoB/archive/refs/heads/update-for-blender-4.zip
