### ISSUE TITLE
After click export crash 

### ISSUE THREAD

**Issue by magicpigomg** [JoseConseco/GoB#441]
Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GoB-3_6_2\GoB.py", line 1426, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "D:\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in call
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Ошибка: Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GoB-3_6_2\GoB.py", line 1340, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GoB-3_6_2\GoB.py", line 967, in exportGoZ
    for i in range(0, len(vcolArray), 3):
UnboundLocalError: local variable 'vcolArray' referenced before assignment
Location: D:\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py:113

**Comment by kromar** [comment]
Can you be a bit more specific what you are exporting? I assume it involves some vertex colors?
Also what version of GoB are you using?

**Comment by magicpigomg** [comment]
I'm using version 3.6.2. This error occurs even when exporting a standard cube.

**Comment by kromar** [comment]
thanks for reporting this issue, it should be fixed in this version: https://github.com/JoseConseco/GoB/releases/tag/v3_6_3
