### ISSUE TITLE
Blender to Zbrush Error 

### ISSUE THREAD

**Issue by gulagenabler** [JoseConseco/GoB#463]
![Screenshot_5](https://github.com/JoseConseco/GoB/assets/98638151/5ec127ea-19e1-4492-a472-f48dbb6a03f1

Tried downloading the GOB version for the version of blender im usng and got this error. tried clean install, closing and reset blender and nothing..

Python: Traceback (most recent call last):
  File "D:\blender-3.6.2\3.6\scripts\addons\GoB-3_6_2\GoB.py", line 1426, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "D:\blender-3.6.2\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\blender-3.6.2\3.6\scripts\addons\GoB-3_6_2\GoB.py", line 1340, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "D:\blender-3.6.2\3.6\scripts\addons\GoB-3_6_2\GoB.py", line 967, in exportGoZ
    for i in range(0, len(vcolArray), 3):
UnboundLocalError: local variable 'vcolArray' referenced before assignment
Location: D:\blender-3.6.2\3.6\scripts\modules\bpy\ops.py:113

**Comment by kromar** [comment]
There is a new release which should fix your issue https://github.com/JoseConseco/GoB/releases/tag/v4_0_3
