### ISSUE TITLE
Blender error 

### ISSUE THREAD

**Issue by AndriyOrlov** [JoseConseco/GoB#466]
Python: Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-4_0_2\GoB.py", line 728, in invoke
    run_import_manually()
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-4_0_2\GoB.py", line 1568, in run_import_manually
    bpy.ops.scene.gob_import() #only call operator update is found (executing operatros is slow)  
  File "D:\Blender\stable\blender-4.0.2+stable.9be62e85b727\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Помилка: Python: Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GoB-4_0_2\GoB.py", line 401, in GoZit
    me.attributes.active_color.data[i].color_srgb = rgba
IndexError: bpy_prop_collection[index]: index 113574 out of range, size 113574
Location: D:\Blender\stable\blender-4.0.2+stable.9be62e85b727\4.0\scripts\modules\bpy\ops.py:109

**Comment by thironaka0716** [comment]
https://github.com/JoseConseco/GoB/issues/465#issuecomment-1993725353

**Comment by kromar** [comment]
There is a new release which should fix your issue https://github.com/JoseConseco/GoB/releases/tag/v4_0_3
