### ISSUE TITLE
many error code when i use the GoB plugin

### ISSUE THREAD

**Issue by Marcoslubian** [JoseConseco/GoB#470]
I install the pugin many times, and it doesn't work well, only works when I run blender the first time, but when I need to use it again nothing happens only a pop up window with error codes, could you help me to fix it please.

this is the code error:

Python: Traceback (most recent call last):
  File "C:\Users\PcCom\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-master\GoB.py", line 728, in invoke
    run_import_manually()
  File "C:\Users\PcCom\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-master\GoB.py", line 1568, in run_import_manually
    bpy.ops.scene.gob_import() #only call operator update is found (executing operatros is slow)  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\PcCom\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-master\GoB.py", line 223, in GoZit
    print("Unknown tag:{0}".format(tag))
OSError: [WinError 233] No hay ningún proceso en el otro extremo de la canalización
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109

**Comment by Marcoslubian** [comment]
first of all thanks for helping me but I still have the same problem, I uninstalled zbrush and blender, I installed again, everything new without the older folder, even I installed in a new hardrive I use the new GoB you send. But the same error again:

bpy.data.window_managers["WinMan"].addon_search = "go"
bpy.context.space_data.system_folders_active = 1
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1477, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1260, in execute
    print(source_GoZ_Info, target_GoZ_Info)
OSError: [WinError 233] No hay ningún proceso en el otro extremo de la canalización

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1277, in execute
    print(e)
OSError: [WinError 233] No hay ningún proceso en el otro extremo de la canalización
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
