### ISSUE TITLE
File not export from blender to zbrush

### ISSUE THREAD

**Issue by douglas3ddesigner** [JoseConseco/GoB#477]
Python: Traceback (most recent call last):
  File "C:\Users\dougm\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1477, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\dougm\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 1391, in execute
    self.exportGoZ(PATH_GOZ, context.scene, obj, f'{PATH_PROJECT}')
  File "C:\Users\dougm\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GoB-4_0_3\GoB.py", line 998, in exportGoZ
    color = active_color.data[loop.index].color_srgb
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: bpy_prop_collection[index]: index 3592 out of range, size 3592
Location: C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py:109
![Screenshot_2](https://github.com/JoseConseco/GoB/assets/9087306/da04bf58-8eca-4be7-969e-8c36f0ef162b)

**Comment by kromar** [comment]
you can find a fix for this issue here: https://github.com/kromar/blender_GoB/tree/fix-vertex-color-out-of-range

**Comment by douglas3ddesigner** [comment]
> you can find a fix for this issue here: https://github.com/kromar/blender_GoB/tree/fix-vertex-color-out-of-range

Thanks Kromar!

**Comment by kromar** [comment]
I made a new release that fixes the error with vertex colors
https://github.com/JoseConseco/GoB/releases/tag/v4_0_4
