### ISSUE TITLE
Export issue at the second user on Mac

### ISSUE THREAD

**Issue by Fornix25** [JoseConseco/GoB#479]
Hi! I created a second Administrator user on Mac and Export doesn't work on it. Please help to resolve this problem& Thanks!

Python: Traceback (most recent call last):
  File "/Users/test/Library/Application Support/Blender/3.6/scripts/addons/GoB-master/GoB.py", line 1468, in invoke
    bpy.ops.scene.gob_export(as_tool=as_tool)
  File "/Applications/Blender 3.6.5.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/test/Library/Application Support/Blender/3.6/scripts/addons/GoB-master/GoB.py", line 1252, in execute
    shutil.copytree(source_GoZ_Info, target_GoZ_Info, symlinks=True)            
  File "/Applications/Blender 3.6.5.app/Contents/Resources/3.6/python/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Applications/Blender 3.6.5.app/Contents/Resources/3.6/python/lib/python3.10/shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/Applications/Blender 3.6.5.app/Contents/Resources/3.6/python/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/Shared/Pixologic/GoZApps/Blender/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/test/Library/Application Support/Blender/3.6/scripts/addons/GoB-master/GoB.py", line 1256, in execute
    shutil.copy2(source_GoZ_Info, target_GoZ_Info)  
  File "/Applications/Blender 3.6.5.app/Contents/Resources/3.6/python/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Applications/Blender 3.6.5.app/Contents/Resources/3.6/python/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/Users/Shared/Pixologic/GoZApps/Blender/GoZ_Info.txt'
Location: /Applications/Blender 3.6.5.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113

**Comment by VertexBeat** [comment]
Same issue.
