### ISSUE TITLE
the imported file has to be installed manually and an error is generated

### ISSUE THREAD

**Issue by robotkurva** [JoseConseco/GoB#484]
Hello! in the new version 4.0.4, after I import the mesh from ZBrush, I see my model immediately when I export it for the first time, then I need to put it through manual export every time. here is the error message 
Python: Traceback (most recent call last):
  File "C:\Users\TomorrowHead\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\GoB-4_0_4\GoB.py", line 746, in invoke
    run_import_manually()
  File "C:\Users\TomorrowHead\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\GoB-4_0_4\GoB.py", line 1585, in run_import_manually
    bpy.ops.scene.gob_import() #only call operator update is found (executing operatros is slow)  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Blender_Download\stable\blender-4.2.0-stable.a51f293548ad\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\TomorrowHead\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\GoB-4_0_4\GoB.py", line 406, in GoZit
    print("error if buffer length is less than 3: ", v, vertex_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'v' where it is not associated with a value
Location: D:\Blender_Download\stable\blender-4.2.0-stable.a51f293548ad\4.2\scripts\modules\bpy\ops.py:109

**Comment by kromar** [comment]
Thanks for reporting this issue. This should be fixed in the latest version.
https://github.com/JoseConseco/GoB/releases/tag/v4_1_0

**Comment by robotkurva** [comment]
Big Thanks for thit!

пн, 9 сент. 2024 г. в 21:23, Daniel G ***@***.***>:
